package TELAS;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import View.ViewLivros;
import View.ViewSlides;
import javax.swing.ImageIcon;

/**
 *
 * @author Windows
 */
public class TelaAdm extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdm
     */
    public TelaAdm() {
        initComponents();
          setExtendedState(MAXIMIZED_BOTH);
        ImageIcon fun = new ImageIcon("src/IMAGENS/nnn].jpg");
        fun.setImage(fun.getImage().getScaledInstance(1366, 1000, 1));
        Imag.setIcon(fun);
        
        ImageIcon conf = new ImageIcon("src/IMAGENS/esse.png");
        conf.setImage(conf.getImage().getScaledInstance(25, 25, 1));
        Set.setIcon(conf);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel = new javax.swing.JPanel();
        sair = new javax.swing.JButton();
        livros = new javax.swing.JButton();
        slides = new javax.swing.JButton();
        telaPrin = new javax.swing.JButton();
        Imag = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        Set = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Painel.setBackground(new java.awt.Color(51, 255, 0));
        Painel.setForeground(new java.awt.Color(255, 255, 255));
        Painel.setLayout(null);

        sair.setBackground(new java.awt.Color(0, 204, 204));
        sair.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        sair.setText("Sair");
        sair.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        Painel.add(sair);
        sair.setBounds(890, 710, 120, 60);

        livros.setBackground(new java.awt.Color(0, 204, 204));
        livros.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        livros.setText(" Livros");
        livros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        livros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                livrosActionPerformed(evt);
            }
        });
        Painel.add(livros);
        livros.setBounds(560, 200, 300, 60);

        slides.setBackground(new java.awt.Color(0, 204, 204));
        slides.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        slides.setText("Slides");
        slides.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        slides.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slidesActionPerformed(evt);
            }
        });
        Painel.add(slides);
        slides.setBounds(600, 360, 220, 60);

        telaPrin.setBackground(new java.awt.Color(0, 204, 204));
        telaPrin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        telaPrin.setText("Tela Principal");
        telaPrin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        telaPrin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telaPrinActionPerformed(evt);
            }
        });
        Painel.add(telaPrin);
        telaPrin.setBounds(640, 510, 160, 60);
        Painel.add(Imag);
        Imag.setBounds(0, 0, 1990, 1000);

        Set.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Set.setPreferredSize(new java.awt.Dimension(50, 30));

        jMenuItem2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem2.setText("Editar nome de Usuário");
        Set.add(jMenuItem2);

        jMenuItem1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem1.setText("Mudar Senha");
        Set.add(jMenuItem1);

        jMenuBar2.add(Set);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel, javax.swing.GroupLayout.DEFAULT_SIZE, 1985, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel, javax.swing.GroupLayout.DEFAULT_SIZE, 984, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void livrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_livrosActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        ViewLivros tela = new ViewLivros();
        tela.setVisible(true);
    }//GEN-LAST:event_livrosActionPerformed

    private void slidesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slidesActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        ViewSlides tela = new ViewSlides();
        tela.setVisible(true);
    }//GEN-LAST:event_slidesActionPerformed

    private void telaPrinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telaPrinActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        TelaPrincipal tela = new TelaPrincipal();
        tela.setVisible(true);
    }//GEN-LAST:event_telaPrinActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_sairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Imag;
    private javax.swing.JPanel Painel;
    private javax.swing.JMenu Set;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JButton livros;
    private javax.swing.JButton sair;
    private javax.swing.JButton slides;
    private javax.swing.JButton telaPrin;
    // End of variables declaration//GEN-END:variables
}
